config/routes.rb
AlquilerMatrix::Application.routes.draw do
  devise_for :users

  resources :movies

  devise_scope :user do
    get "login", to: "devise/sessions#new", as: :login
    get "logout", to: "devise/sessions#destroy", as: :logout
    get "register", to: "devise/registrations#new", as: :register
  end

  root :to => 'movies#index'
  get "search", to: "movies#search"

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :actors, :description, :duration, :genre, :language, :rate, :release, :title, :image

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
  validates :title, presence: true
  validates :genre, presence: true
  validates :release, presence: true
  validates :rate, presence: true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :set_movie, only: [:show, :edit, :update, :destroy]
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.order('title asc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  def search
    @movies = Movie.where("title LIKE ?", params[:search])
    render 'index'
  end

  private

  def set_movie
    @movie =  Movie.find(params[:id])
  end
  def  movie_params
    params.requiere(:movie).permit(:image, :title)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Alquiler Matrix', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>

        <li>
          <%=
          link_to current_user.email, edit_user_registration_path
          %>
        </li>
        <li>
          <%=
          link_to 'Log Out', logout_path, method: :get
          %>
        </li>

        <% else %>

        <li>
          <%=
           link_to 'Sign In', login_path, class: "button"
          %>
        </li>

        <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Alquiler Matrix" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Alquiler Matrix" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <div class="large-12 columns">
        <%= yield %>
       </div>
    </main>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div></div>
  <div class="row">
  <div class="small-4">

    <%= f.label :genre %><br />
    <%= f.text_field :genre %>


    <%= f.label :actors %><br />
    <%= f.text_field :actors %>


    <%= f.label :duration %><br />
    <%= f.text_field :duration %>


    <%= f.label :release %><br />
    <%= f.date_select  :release %>


  <div class="field">
    <%= f.label :rate %><br />
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  </div></div>
  <div class="actions">
    <%= f.submit nil, class: "button round" %>
  </div>
<% end %>

app/views/movies/_search.html.erb
<div class="small-8 columns">
<%= form_tag({:controller => "movies", :action => "search"}, :method => "get") do %>
<label>Movie title
  <%= text_field_tag :search, params[:search], :id => 'search_field' %>
  </label>
  <%= submit_tag "Search", :name => nil,class: 'button [tiny small radius round]' %>
<% end %>
</div>
<div class="small-4 columns">
<!-- <label>Genre
<select>
    <option value='-1'>Todos</option>
    <option value='Drama'>Drama</option>
    <option value='Accion'>Accion</option>
    <option value='Terror'>Terror</option>
    <option value='Suspenso'>Suspenso</option>
    <option value='Comedia'>Comedia</option>
    </select>
    </label>
-->
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>
<div class="row">
 <div id="search">
    <%= render :partial => 'movies/search' %>
  </div>
<div class="large-12 columns">
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Genre</th>
    <th>Image</th>
    <th></th>
    <% if user_signed_in? %>

    <th></th>
    <th></th>
    <% end %>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.title %></td>
    <td><%= movie.description %></td>
    <td><%= movie.genre %></td>
    <td><%= image_tag movie.image.url(:thumb) %></td>
    <td><%= link_to 'Show', movie %></td>
    <% if user_signed_in? %>

    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     <% end %>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in? %>
    <%= link_to 'New Movie', new_movie_path %> |
    <%= link_to 'Sign Up', register_path %>
<% end %>
</div>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Description:</b>
  <%= @movie.description %>
</p>

<p>
  <b>Genre:</b>
  <%= @movie.genre %>
</p>

<p>
  <b>Actors:</b>
  <%= @movie.actors %>
</p>

<p>
  <b>Duration:</b>
  <%= @movie.duration %>
</p>

<p>
  <b>Release:</b>
  <%= @movie.release %>
</p>

<p>
  <b>Rate:</b>
  <%= @movie.rate %>
</p>

<p>
  <b>Language:</b>
  <%= @movie.language %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @movie.image.url(:medium) %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>